import { type PoolClient } from "pg";
import { buildEconomyMetrics, getEconomyMultiplier } from "@/server/season-economy";

type DbExecutor = Pick<PoolClient,"query">;
type SpinMetrics={hour:number;day:number;week:number;season:number};
type DropPrize={kind:string;title:string;subtitle?:string|null;amount?:number;unitCost?:number;currency?:string|null;quantityTotal:number;quantityRemaining?:number;active?:boolean;imageUrl?:string|null;metadata?:Record<string,unknown>};
type DropPayload={prizes?:DropPrize[]};
const ALLOWED_KINDS=new Set(["STARS","PREMIUM","MONEY","NFT","PHYSICAL","CUSTOM","FREE_SPIN","EMPTY"]);
export async function reconcileSeasonStates(db:DbExecutor){const transitioned:Array<{id:string;code:string;from:string;to:string}>=[];const due=await db.query<{id:string;code:string}>(`SELECT id::text,code FROM seasons WHERE state='SCHEDULED' AND starts_at IS NOT NULL AND starts_at<=now() ORDER BY starts_at ASC,created_at ASC LIMIT 1`);if(due.rows[0]){await db.query(`UPDATE seasons SET state='CLOSED',updated_at=now() WHERE state IN ('ACTIVE','ENDING') AND id<>$1::uuid`,[due.rows[0].id]);const activated=await db.query<{id:string;code:string}>(`UPDATE seasons SET state='ACTIVE',updated_at=now() WHERE id=$1::uuid AND state='SCHEDULED' RETURNING id::text,code`,[due.rows[0].id]);if(activated.rows[0])transitioned.push({id:activated.rows[0].id,code:activated.rows[0].code,from:"SCHEDULED",to:"ACTIVE"});}const ended=await db.query<{id:string;code:string}>(`UPDATE seasons SET state='ENDING',updated_at=now() WHERE state='ACTIVE' AND ends_at IS NOT NULL AND ends_at<=now() RETURNING id::text,code`);for(const season of ended.rows)transitioned.push({id:season.id,code:season.code,from:"ACTIVE",to:"ENDING"});const closing=await db.query<{id:string;code:string}>(`UPDATE seasons SET state='CLOSED',updated_at=now() WHERE state='ENDING' AND ends_at IS NOT NULL AND ends_at<=now() RETURNING id::text,code`);for(const season of closing.rows)transitioned.push({id:season.id,code:season.code,from:"ENDING",to:"CLOSED"});return transitioned;}
export async function collectSeasonSpinMetrics(db:DbExecutor,seasonId:string):Promise<SpinMetrics>{const r=await db.query<{hour:string;day:string;week:string;season:string}>(`SELECT COUNT(*) FILTER (WHERE created_at>=now()-interval '1 hour')::text hour,COUNT(*) FILTER (WHERE created_at>=now()-interval '1 day')::text day,COUNT(*) FILTER (WHERE created_at>=now()-interval '7 days')::text week,COUNT(*)::text season FROM spins WHERE season_id=$1::uuid AND status='COMPLETED'`,[seasonId]);const x=r.rows[0];return{hour:Number(x?.hour??0),day:Number(x?.day??0),week:Number(x?.week??0),season:Number(x?.season??0)};}
export async function writeEconomySnapshot(db:DbExecutor,season:{id:string;startsAt:string|null;endsAt:string|null}){const spins=await collectSeasonSpinMetrics(db,season.id);const metrics=buildEconomyMetrics({startsAt:season.startsAt,endsAt:season.endsAt,spins});const rows=await db.query<{id:string;quantity_total:number;quantity_remaining:number}>(`SELECT id::text,quantity_total,quantity_remaining FROM prizes WHERE season_id=$1::uuid AND is_active=TRUE ORDER BY created_at`,[season.id]);const multipliers:Record<string,number>={};for(const row of rows.rows){multipliers[row.id]=getEconomyMultiplier({quantityTotal:row.quantity_total,quantityRemaining:row.quantity_remaining,elapsedFraction:metrics.elapsedFraction});}await db.query(`INSERT INTO season_economy_snapshots(season_id,completed_spins,spins_last_hour,spins_last_day,spins_last_week,pace_per_day,projected_season_spins,multipliers) VALUES($1::uuid,$2,$3,$4,$5,$6,$7,$8::jsonb)`,[season.id,metrics.completedSpins,spins.hour,spins.day,spins.week,metrics.pacePerDay,metrics.projectedSeasonSpins,JSON.stringify(multipliers)]);return{metrics,multipliers};}
function parseDropPayload(v:unknown):DropPayload{if(!v||typeof v!=="object")return{};const p=v as DropPayload;return Array.isArray(p.prizes)?{prizes:p.prizes}:{};}
function validatePrize(p:DropPrize){return Boolean(ALLOWED_KINDS.has(p.kind)&&p.title?.trim()&&Number.isInteger(p.quantityTotal)&&p.quantityTotal>=1&&Number.isFinite(p.amount??0)&&(p.amount??0)>=0&&Number.isFinite(p.unitCost??0)&&(p.unitCost??0)>=0&&(p.quantityRemaining===undefined||(Number.isInteger(p.quantityRemaining)&&p.quantityRemaining>=0&&p.quantityRemaining<=p.quantityTotal)));}
async function executeDrop(db:DbExecutor,drop:{id:string;payload:unknown},seasonId:string){const payload=parseDropPayload(drop.payload);if(!payload.prizes?.length||!payload.prizes.every(validatePrize))throw new Error("INVALID_DROP_PAYLOAD");for(const prize of payload.prizes){const total=prize.quantityTotal;const remaining=prize.quantityRemaining??total;await db.query(`INSERT INTO prizes(season_id,kind,title,subtitle,amount,unit_cost,currency,quantity_total,quantity_remaining,is_active,image_url,metadata) VALUES($1::uuid,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb)`,[seasonId,prize.kind,prize.title.trim(),prize.subtitle??null,prize.amount??0,prize.unitCost??0,prize.currency??null,total,remaining,prize.active!==false,prize.imageUrl??null,JSON.stringify({...prize.metadata??{},liveOpsDropId:drop.id})]);}await db.query(`UPDATE season_drop_events SET status='EXECUTED',executed_at=now(),updated_at=now() WHERE id=$1::uuid`,[drop.id]);}
export async function activateDropById(db:DbExecutor,seasonId:string,dropId:string){const r=await db.query<{id:string;payload:unknown;status:string}>(`SELECT id::text,payload,status FROM season_drop_events WHERE id=$1::uuid AND season_id=$2::uuid FOR UPDATE`,[dropId,seasonId]);if(!r.rows[0])throw new Error("DROP_NOT_FOUND");if(r.rows[0].status!=="SCHEDULED")throw new Error("DROP_NOT_SCHEDULED");await executeDrop(db,r.rows[0],seasonId);}
export async function activateDueDrops(db:DbExecutor,seasonId:string){const r=await db.query<{id:string;payload:unknown}>(`SELECT id::text,payload FROM season_drop_events WHERE season_id=$1::uuid AND status='SCHEDULED' AND ((trigger_type='AT' AND trigger_value IS NOT NULL AND trigger_value<=extract(epoch FROM now())) OR (trigger_type='SEASON_PERCENT' AND trigger_value IS NOT NULL AND trigger_value<=COALESCE((SELECT CASE WHEN ends_at>starts_at THEN 100.0*EXTRACT(EPOCH FROM(now()-starts_at))/NULLIF(EXTRACT(EPOCH FROM(ends_at-starts_at)),0) ELSE 0 END FROM seasons WHERE id=$1::uuid),0)) OR (trigger_type='SPIN_COUNT' AND trigger_value IS NOT NULL AND trigger_value<=(SELECT COUNT(*) FROM spins WHERE season_id=$1::uuid AND status='COMPLETED'))) ORDER BY created_at ASC FOR UPDATE`,[seasonId]);const executed:string[]=[];for(const drop of r.rows){const payload=parseDropPayload(drop.payload);if(!payload.prizes?.length||!payload.prizes.every(validatePrize)){await db.query(`UPDATE season_drop_events SET status='CANCELLED',updated_at=now() WHERE id=$1::uuid`,[drop.id]);continue;}await executeDrop(db,drop,seasonId);executed.push(drop.id);}return executed;}
