import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Gift, Plus, Send, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/kit/AppShell";
import { GlassCard } from "@/components/kit/GlassCard";
import { ExportListButton } from "@/components/kit/ExportListButton";
import { t } from "@/lib/i18n";

export const Route = createFileRoute("/admin/owner-gifts")({ head:()=>({meta:[{title:"Личные подарки — CRICKET BOX"}]}), component:OwnerGifts });
type GiftRow={id:string;username:string;telegramId:string;gift:string;status:"Подготовлен"|"Выдан"|"Ожидает";message:string;createdAt:string;issuedAt:string|null;rewardType?:string;amount?:number;rewardApplied?:boolean};
type Api={ok:boolean;gifts?:GiftRow[];code?:string};
function initData(){if(typeof window==="undefined")return "";return (window as Window&{Telegram?:{WebApp?:{initData?:string}}}).Telegram?.WebApp?.initData?.trim()??"";}
async function request<T>(url:string,method:"GET"|"POST"|"PATCH",body?:Record<string,unknown>){const response=await fetch(url,{method,headers:{"content-type":"application/json"},...(body?{body:JSON.stringify({...body,initData:initData()})}:{})});const data=await response.json() as T&{ok?:boolean;code?:string};if(!response.ok||data.ok!==true)throw new Error(data.code??"REQUEST_FAILED");return data;}
function OwnerGifts(){
 const [rows,setRows]=useState<GiftRow[]>([]);const [username,setUsername]=useState("");const [telegramId,setTelegramId]=useState("");const [gift,setGift]=useState("Особый подарок владельца");const [message,setMessage]=useState("");const [rewardType,setRewardType]=useState("NOTE");const [amount,setAmount]=useState("5");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const data=await request<Api>(`/api/admin/owner-gifts?initData=${encodeURIComponent(initData())}`,"GET");setRows(data.gifts??[]);}catch(e){setError(e instanceof Error?e.message:t("ownerGifts.loadFailed"));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function addGift(){if(!telegramId.trim()||!gift.trim())return;setSaving(true);setError("");try{const data=await request<Api>("/api/admin/owner-gifts","POST",{telegramId,username,gift,message,rewardType,amount:Number(amount)});if(data.gifts)setRows(data.gifts);setTelegramId("");setUsername("");setMessage("");}catch(e){setError(e instanceof Error?e.message:t("ownerGifts.prepareFailed"));}finally{setSaving(false);}}
 async function setStatus(id:string,status:"Подготовлен"|"Ожидает"|"Выдан"){setSaving(true);setError("");try{const data=await request<Api>("/api/admin/owner-gifts","PATCH",{id,status});setRows(data.gifts??[]);}catch(e){setError(e instanceof Error?e.message:t("ownerGifts.statusFailed"));}finally{setSaving(false);}}
 return <AppShell title={t("ownerGifts.title")} nav={false}><div className="space-y-4 pb-8"><Link to="/admin" className="inline-flex items-center gap-2 text-[11px] text-muted-foreground"><ArrowLeft className="size-3.5"/> {t("settingsAdmin.back")}</Link>
  <GlassCard className="px-4 py-4" glow><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl border border-glass-border bg-muted/20"><Gift className="size-5 text-primary-glow"/></div><div><p className="text-[10px] uppercase tracking-[0.22em] text-muted-foreground">{t("ownerGifts.fromOwner")}</p><h1 className="mt-1 font-display text-xl uppercase">{t("ownerGifts.heading")}</h1><p className="mt-1 text-[11px] text-muted-foreground">{t("ownerGifts.description")}</p></div></div></GlassCard>
  <GlassCard className="space-y-3 px-3 py-3"><div className="flex items-center gap-2"><UserRound className="size-4 text-primary-glow"/><p className="text-sm font-semibold">{t("ownerGifts.newGift")}</p></div><input value={username} onChange={e=>setUsername(e.target.value)} placeholder={t("ownerGifts.username")} className="admin-input w-full"/><input value={telegramId} onChange={e=>setTelegramId(e.target.value.replace(/\D/g,""))} placeholder={t("ownerGifts.telegramId")} inputMode="numeric" className="admin-input w-full"/><input value={gift} onChange={e=>setGift(e.target.value)} placeholder={t("ownerGifts.gift")} className="admin-input w-full"/><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder={t("ownerGifts.message")} className="admin-input min-h-20 w-full resize-none"/><select value={rewardType} onChange={e=>setRewardType(e.target.value)} className="admin-input w-full"><option value="NOTE">Только сообщение</option><option value="STARS">⭐ Stars</option><option value="FREE_SPIN">🎲 Бесплатные прокрутки</option><option value="XP">✨ XP</option></select>{rewardType!=="NOTE"&&<input type="number" min={1} value={amount} onChange={e=>setAmount(e.target.value)} className="admin-input w-full" placeholder="Количество"/>}<button disabled={saving} type="button" onClick={()=>void addGift()} className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-primary/30 bg-primary/10 px-3 py-2.5 text-xs font-semibold"><Plus className="size-4"/>{saving?t("ownerGifts.saving"):t("ownerGifts.prepare")}</button></GlassCard>
  {error&&<GlassCard className="border-destructive/30 bg-destructive/5 px-4 py-3 text-[11px] text-destructive">{error}</GlassCard>}
  <section><div className="mb-2 flex items-center justify-between gap-2"><h2 className="section-label">{t("ownerGifts.history")}</h2><div className="flex items-center gap-2"><ExportListButton filename="lichnye-podarki" title="Личные подарки" headers={["Username","Telegram ID","Подарок","Статус","Награда","Количество","Создан"]} rows={rows.map(r=>[r.username,r.telegramId,r.gift,r.status,r.rewardType==="STARS"?"Stars":r.rewardType==="FREE_SPIN"?"Free Spin":r.rewardType==="XP"?"XP":"—",r.amount??"—",new Date(r.createdAt).toLocaleString("ru-RU")])}/><button type="button" onClick={()=>void load()} className="text-[10px] text-primary-glow">{t("ownerGifts.refresh")}</button></div></div>{loading?<GlassCard className="px-4 py-8 text-center text-xs text-muted-foreground">{t("ownerGifts.loading")}</GlassCard>:<div className="space-y-2.5">{rows.length===0?<GlassCard className="px-4 py-8 text-center text-xs text-muted-foreground">{t("ownerGifts.empty")}</GlassCard>:rows.map(row=><GlassCard key={row.id} className="px-3.5 py-3.5"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{row.gift}</p><p className="mt-1 text-[10px] text-muted-foreground">{row.username} · Telegram ID: {row.telegramId}</p>{row.message&&<p className="mt-1 text-[10px] text-muted-foreground">{t("ownerGifts.messageLabel")} {row.message}</p>}{row.rewardType&&row.rewardType!=="NOTE"&&<p className="mt-1 text-[10px] text-primary-glow">Награда: {row.amount} {row.rewardType==="STARS"?"⭐":row.rewardType==="FREE_SPIN"?"бесплатных прокруток":"XP"}{row.rewardApplied?" · зачислено ✅":""}</p>}<p className="mt-1 text-[10px] text-muted-foreground">{t("ownerGifts.created")} {new Date(row.createdAt).toLocaleString("ru-RU",{hour12:false})}</p></div><span className="rounded-full border border-glass-border px-2 py-1 text-[9px]">{row.status}</span></div>{row.status!=="Выдан"&&<div className="mt-3 grid grid-cols-2 gap-2 border-t border-glass-border pt-3"><button disabled={saving} type="button" onClick={()=>void setStatus(row.id,"Подготовлен")} className="rounded-xl border border-glass-border bg-muted/10 px-3 py-2 text-[10px] font-semibold">Подготовлен</button><button disabled={saving} type="button" onClick={()=>void setStatus(row.id,"Выдан")} className="inline-flex items-center justify-center gap-2 rounded-xl border border-primary/25 bg-primary/5 px-3 py-2 text-[10px] font-semibold"><Send className="size-3.5"/> Выдан</button></div>}</GlassCard>)}</div>}</section>
  <GlassCard className="px-4 py-3 text-[10px] leading-relaxed text-muted-foreground">{t("ownerGifts.queueNotice")}</GlassCard>
 </div></AppShell>;
}
