import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowLeft, CheckCircle2, Flame, Gift, RefreshCw, Users } from 'lucide-react';
import { useEffect,useMemo,useState } from 'react';
import { AppShell } from '@/components/kit/AppShell';
import { GlassCard } from '@/components/kit/GlassCard';
export const Route=createFileRoute('/admin/daily-streak')({head:()=>({meta:[{title:'Daily Streak — CRICKET BOX'}]}),component:DailyStreakAdmin});
type Player={id:string;telegramId:string;username:string;name:string;totalDays:number;currentDay:number;visitedDays:number;currentStreak:number;checkedInToday:boolean;eligibleForReward:boolean;days:number[];day7Choice:{type:string;amount:number;cycleNo:number}|null};
type Api={ok:boolean;code?:string;season?:{name:string;code:string;state:string;startsAt:string|null;endsAt:string|null;closedAt:string|null;totalDays:number;currentDay:number;live:boolean};metrics?:{participants:number;checkedToday:number;notCheckedToday:number;noMisses:number;eligible:number;starsSchedule:number[]};players?:Player[]};
function initData(){return typeof window==='undefined'?'':(window as Window & {Telegram?:{WebApp?:{initData?:string}}}).Telegram?.WebApp?.initData?.trim()??'';}
function dt(v:string|null){return v?new Date(v).toLocaleString('ru-RU',{dateStyle:'short',timeStyle:'short'}):'—';}
function DailyStreakAdmin(){
const [data,setData]=useState<Api|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState('');
async function load(){setLoading(true);setError('');try{const r=await fetch('/api/admin/daily-streak?initData='+encodeURIComponent(initData())+'&_='+Date.now(),{cache:'no-store'});const d=await r.json() as Api;if(!r.ok||!d.ok)throw new Error(d.code??'DAILY_STREAK_FAILED');setData(d);}catch{setError('Не удалось загрузить Daily Streak.');}finally{setLoading(false);}}
useEffect(()=>{void load();const id=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(id);},[]);
const players=useMemo(()=>{const q=search.trim().toLowerCase();return(data?.players??[]).filter(p=>!q||p.name.toLowerCase().includes(q)||p.username.toLowerCase().includes(q)||p.telegramId.includes(q));},[data,search]);
const s=data?.season,m=data?.metrics;
return <AppShell title='Daily Streak' nav={false}><div className='space-y-4 pb-8'><Link to='/admin' className='inline-flex items-center gap-2 text-[11px] text-muted-foreground'><ArrowLeft className='size-3.5'/> Админ-панель</Link>{error&&<GlassCard className='border-destructive/30 bg-destructive/5 px-4 py-3 text-[11px] text-destructive'>{error}</GlassCard>}{loading&&!data?<GlassCard className='px-4 py-8 text-center text-xs text-muted-foreground'>Загрузка…</GlassCard>:s&&m&&<>
<GlassCard glow className='px-4 py-4'><div className='flex items-start justify-between gap-3'><div><p className='text-[10px] uppercase tracking-[0.22em] text-muted-foreground'>🔥 Daily Streak</p><h1 className='mt-1 font-display text-xl uppercase'>{s.name}</h1><p className='mt-1 text-[10px] text-muted-foreground'>{s.live?'Текущий день: '+Math.min(7,s.currentDay)+' / 7':'Сезон завершён '+dt(s.closedAt)+' · серия остановлена'}</p></div><button type='button' onClick={()=>void load()} className='grid size-9 place-items-center rounded-xl border border-glass-border bg-muted/10'><RefreshCw className='size-4'/></button></div><div className='mt-4 grid grid-cols-2 gap-2 md:grid-cols-5'><Metric icon={Users} label='Участники' value={String(m.participants)}/><Metric icon={CheckCircle2} label='Сегодня' value={String(m.checkedToday)}/><Metric icon={Flame} label='Без пропусков' value={String(m.noMisses)}/><Metric icon={Gift} label='Готовы к дню 7' value={String(m.eligible)}/><Metric icon={Flame} label='День сезона' value={String(s.currentDay)}/></div></GlassCard>
<GlassCard className='px-4 py-4'><h2 className='text-sm font-semibold'>Как теперь работает серия</h2><p className='mt-1 text-[10px] text-muted-foreground'>Серия всегда состоит из 7 дней. Первые 6 дней автоматически дают 10 ⭐.</p><div className='mt-3 grid grid-cols-7 gap-1.5'>{(m.starsSchedule??[1,1,1,2,2,3]).map((reward,i)=><div key={i} className='rounded-xl border border-glass-border bg-muted/10 px-1 py-2 text-center'><div className='mx-auto grid size-7 place-items-center rounded-lg bg-muted/20 font-semibold'>{i+1}</div><p className='mt-1 text-[8px] text-muted-foreground'>День {i+1}</p><p className='mt-1 text-[9px] font-semibold'>+{reward} ⭐</p></div>)}<div className='rounded-xl border border-primary/40 bg-primary/10 px-1 py-2 text-center'><div className='mx-auto grid size-7 place-items-center rounded-lg bg-primary/20'>🎁</div><p className='mt-1 text-[8px]'>День 7</p><p className='mt-1 text-[8px] font-semibold'>Выбор</p></div></div><div className='mt-3 rounded-2xl border border-primary/20 bg-primary/5 px-3 py-3 text-[10px] leading-relaxed'>⭐ +5 Stars · 🎟️ +1 бонусная попытка · 🍀 +20% к Daily Gift · ⚡ буст следующей прокрутки</div>{!s.live&&<p className='mt-3 rounded-xl border border-glass-border bg-muted/10 px-3 py-2.5 text-[10px] text-muted-foreground'>Сезон закрыт. Новые дни и награды серии больше не начисляются.</p>}</GlassCard>
<section><div className='mb-2 flex items-center justify-between gap-2'><div><h2 className='section-label'>Участники</h2><p className='text-[10px] text-muted-foreground'>{players.length} записей</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder='Имя, @username или ID' className='admin-input max-w-[220px]'/></div><div className='space-y-2'>{players.map(p=><GlassCard key={p.id} className='px-3.5 py-3.5'><div className='flex items-start gap-3'><div className='grid size-9 place-items-center rounded-xl border border-orange-400/20 bg-orange-500/10'>🔥</div><div className='min-w-0 flex-1'><p className='text-sm font-semibold'>{p.name} <span className='text-[10px] font-normal text-muted-foreground'>{p.username}</span></p><p className='mt-1 text-[10px] text-muted-foreground'>🔥 {p.currentStreak} подряд · {p.visitedDays}/7 дней · {p.checkedInToday?'сегодня ✅':'сегодня ❌'}</p><div className='mt-2 grid grid-cols-7 gap-1'>{Array.from({length:7},(_,i)=>i+1).map(day=><span key={day} title={'День '+day} className={`h-4 rounded-[5px] border ${p.days.includes(day)?'border-primary/50 bg-primary/70':'border-glass-border bg-muted/20'}`}/>)}</div>{p.day7Choice&&<p className='mt-2 text-[9px] text-primary-glow'>День 7: {p.day7Choice.type} · {p.day7Choice.amount} · цикл {p.day7Choice.cycleNo}</p>}</div><div className='shrink-0 text-right'>{p.eligibleForReward?'🎁 Готов':'—'}</div></div></GlassCard>)}{players.length===0&&<GlassCard className='px-4 py-8 text-center text-xs text-muted-foreground'>Нет данных.</GlassCard>}</div></section>
</>}</div></AppShell>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string}){return <div className='rounded-2xl border border-glass-border bg-muted/20 px-3 py-3'><Icon className='size-4 text-primary-glow'/><p className='mt-2 text-[9px] uppercase tracking-[0.12em] text-muted-foreground'>{label}</p><p className='mt-1 font-display text-lg'>{value}</p></div>}