import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Crown, History, Medal, ShieldCheck, Sparkles, Users, Power } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/kit/AppShell";
import { GlassCard } from "@/components/kit/GlassCard";

export const Route=createFileRoute("/admin/veteran")({head:()=>({meta:[{title:"Бонусы ветеранов — CRICKET BOX"}]}),component:VeteranBuffs});
type Tier="ROOKIE"|"VETERAN"|"ELITE";
type Player={id:string;telegramId:string;username:string;name:string;seasons:number;spins:number;wins:number;tier:Tier;bonusIssued:number;bonusUsed:number;bonusRemaining:number};
type Rule={tier:Tier;label:string;minSeasons:number;bonusSpins:number;description:string};
type Api={ok:boolean;enabled?:boolean;rules?:Rule[];players?:Player[];code?:string};
function initData(){if(typeof window==="undefined")return "";return (window as Window&{Telegram?:{WebApp?:{initData?:string}}}).Telegram?.WebApp?.initData?.trim()??"";}
function tierLabel(tier:Tier){return tier==="ELITE"?"Элита":tier==="VETERAN"?"Ветеран":"Новичок";}
function VeteranBuffs(){
 const [players,setPlayers]=useState<Player[]>([]);const [rules,setRules]=useState<Rule[]>([]);const [enabled,setEnabled]=useState(true);const [tierFilter,setTierFilter]=useState<Tier|"ALL">("ALL");const [loading,setLoading]=useState(true);const [working,setWorking]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch(`/api/admin/veteran?initData=${encodeURIComponent(initData())}`);const d=await r.json() as Api;if(!r.ok||!d.ok)throw new Error(d.code??"REQUEST_FAILED");setPlayers(d.players??[]);setRules(d.rules??[]);setEnabled(d.enabled!==false);}catch{setError("Не удалось загрузить ветеранскую систему.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function toggleSystem(){setWorking(true);setError("");try{const r=await fetch("/api/admin/veteran",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({initData:initData(),enabled:!enabled})});const d=await r.json() as Api;if(!r.ok||!d.ok)throw new Error(d.code??"REQUEST_FAILED");setEnabled(!enabled);setMessage(!enabled?"Бонусы ветеранов включены.":"Бонусы ветеранов выключены.");}catch(e){setError(e instanceof Error&&e.message==="OWNER_ONLY"?"Только владелец может менять системную настройку.":"Не удалось изменить настройку.");}finally{setWorking(false);}}
 const filtered=useMemo(()=>players.filter(p=>tierFilter==="ALL"||p.tier===tierFilter),[players,tierFilter]);const counts={elite:players.filter(x=>x.tier==="ELITE").length,veteran:players.filter(x=>x.tier==="VETERAN").length,rookie:players.filter(x=>x.tier==="ROOKIE").length};
 return <AppShell title="Бонусы ветеранов" nav={false}><div className="space-y-4 pb-8"><Link to="/admin" className="inline-flex items-center gap-2 text-[11px] text-muted-foreground"><ArrowLeft className="size-3.5"/> Админ-панель</Link>
  <GlassCard className="px-4 py-4" glow><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[0.22em] text-muted-foreground">Реальная история PostgreSQL</p><h1 className="mt-1 font-display text-xl uppercase">Бонусы ветеранов</h1><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">Система смотрит на завершённые предыдущие сезоны. При входе в новый сезон бонус выдаётся один раз и затем списывается отдельной попыткой.</p></div><Crown className="size-5 text-primary-glow"/></div><div className="mt-4 grid grid-cols-3 gap-2"><Metric icon={Medal} label="Элита" value={String(counts.elite)}/><Metric icon={ShieldCheck} label="Ветераны" value={String(counts.veteran)}/><Metric icon={Users} label="Новички" value={String(counts.rookie)}/></div></GlassCard>
  <GlassCard className="flex items-center justify-between gap-3 px-4 py-3"><div><p className="text-sm font-semibold">Система бонусов</p><p className="text-[10px] text-muted-foreground">{enabled?"Включена и выдаёт бонусы автоматически.":"Выключена: новые бонусы не выдаются."}</p></div><button disabled={working} type="button" onClick={()=>void toggleSystem()} className="inline-flex items-center gap-1.5 rounded-xl border border-primary/25 bg-primary/10 px-3 py-2 text-[10px] font-semibold"><Power className="size-3.5"/>{enabled?"Выключить":"Включить"}</button></GlassCard>
  {message&&<GlassCard className="border-primary/25 bg-primary/5 px-4 py-3 text-[11px]">{message}</GlassCard>}{error&&<GlassCard className="border-destructive/30 bg-destructive/5 px-4 py-3 text-[11px] text-destructive">{error}</GlassCard>}
  <section><h2 className="section-label mb-2">Правила</h2><div className="space-y-2.5">{rules.map(rule=><GlassCard key={rule.tier} className="px-3.5 py-3.5"><div className="flex items-start gap-3"><div className="grid size-9 place-items-center rounded-xl border border-glass-border bg-muted/20"><Sparkles className="size-4 text-primary-glow"/></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{rule.label}</p><p className="mt-1 text-[10px] text-muted-foreground">От {rule.minSeasons} завершённых сезонов · +{rule.bonusSpins} бонусных попытки на новый сезон</p><p className="mt-1 text-[10px] leading-relaxed text-muted-foreground">{rule.description}</p></div></div></GlassCard>)}</div></section>
  <GlassCard className="px-3 py-3"><div className="flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{(["ALL","ROOKIE","VETERAN","ELITE"] as const).map(item=><button key={item} type="button" onClick={()=>setTierFilter(item)} className={`shrink-0 rounded-full border px-3 py-1.5 text-[10px] font-semibold ${tierFilter===item?"border-primary/40 bg-primary/10":"border-glass-border bg-muted/10 text-muted-foreground"}`}>{item==="ALL"?"Все":tierLabel(item)}</button>)}</div></GlassCard>
  <section><div className="mb-2 flex items-center justify-between"><h2 className="section-label">Пользователи</h2><button type="button" onClick={()=>void load()} className="text-[10px] text-primary-glow">Обновить</button></div>{loading?<GlassCard className="px-4 py-8 text-center text-xs text-muted-foreground">Считаем историю сезонов…</GlassCard>:<div className="space-y-2.5">{filtered.map(player=><GlassCard key={player.id} className="px-3.5 py-3.5"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{player.name}</p><span className="rounded-full border border-glass-border px-2 py-0.5 text-[9px]">{tierLabel(player.tier)}</span></div><p className="mt-1 text-[10px] text-muted-foreground">{player.username} · Telegram ID: {player.telegramId}</p><p className="mt-1 text-[10px] text-muted-foreground">Сезонов: {player.seasons} · прокруток: {player.spins} · побед: {player.wins}</p><p className="mt-2 text-[10px] text-muted-foreground">Бонусы: выдано {player.bonusIssued} · использовано {player.bonusUsed} · осталось <strong className="text-foreground">{player.bonusRemaining}</strong></p></div><div className="rounded-xl border border-glass-border bg-muted/10 px-3 py-2 text-center"><p className="text-[9px] text-muted-foreground">Статус</p><p className="mt-1 text-[10px] font-semibold">{player.bonusRemaining>0?"Есть бонус":"Нет бонуса"}</p></div></div></GlassCard>)}{filtered.length===0&&<GlassCard className="px-4 py-8 text-center text-xs text-muted-foreground">Пользователей с такой историей пока нет.</GlassCard>}</div>}</section>
  <GlassCard className="px-4 py-3 text-[10px] leading-relaxed text-muted-foreground"><div className="flex items-start gap-2"><History className="mt-0.5 size-4 shrink-0 text-primary-glow"/><p><strong className="text-foreground">Логика:</strong> 2 завершённых сезона → Ветеран и +1 бонусная попытка. 4+ → Элита и +2. Бонус выдаётся при первом открытии нового активного сезона. Тестовые аккаунты скрыты.</p></div></GlassCard>
 </div></AppShell>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Medal;label:string;value:string}){return <div className="rounded-2xl border border-glass-border bg-muted/20 px-3 py-3"><Icon className="size-4 text-primary-glow"/><p className="mt-2 text-[9px] uppercase tracking-[0.16em] text-muted-foreground">{label}</p><p className="mt-1 font-display text-lg">{value}</p></div>;}
