import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowLeft, Gift, HandCoins, Power, Shuffle, Sparkles, Ticket, Star, Zap } from 'lucide-react';
import { useEffect, useState } from 'react';
import { AppShell } from '@/components/kit/AppShell';
import { GlassCard } from '@/components/kit/GlassCard';

export const Route=createFileRoute('/admin/mechanics')({head:()=>({meta:[{title:'Развлекательные механики — CRICKET BOX'}]}),component:Mechanics});
type Settings={enabled:Record<string,boolean>;passCount:number;failureText:string;confirm:boolean};
type Api={ok:boolean;settings?:Settings;event?:{id:string;type:string;status:string;telegramId:string;username:string;payload:Record<string,unknown>;createdAt:string};code?:string};
const MECHANICS=[
 {id:'gift-or-pass',title:'Оставить подарок или передать дальше',description:'Пользователь получает отдельный подарок и может передать его другому участнику ограниченное число раз.',icon:Gift},
 {id:'good-or-bad',title:'Хороший или неудачный подарок',description:'Самостоятельное развлекательное событие без списания накопленных Stars и без изменения основного prize pool.',icon:Shuffle},
 {id:'owner-special',title:'Особый подарок владельца',description:'Персональный подарок конкретному пользователю с реальным начислением при открытии.',icon:Zap},
] as const;
function initData(){return typeof window==='undefined'?'':(window as Window & {Telegram?:{WebApp?:{initData?:string}}}).Telegram?.WebApp?.initData?.trim()??'';}
async function request<T>(url:string,method:'GET'|'POST'|'PATCH',body?:Record<string,unknown>){const response=await fetch(url,{method,headers:{'content-type':'application/json'},...(body?{body:JSON.stringify({...body,initData:initData()})}:{})});const data=await response.json() as T&{ok?:boolean;code?:string};if(!response.ok||data.ok!==true)throw new Error(data.code??'REQUEST_FAILED');return data;}
function Mechanics(){
 const [settings,setSettings]=useState<Settings>({enabled:{'gift-or-pass':true,'good-or-bad':false,'owner-special':true},passCount:2,failureText:'Не повезло… но это было красиво 😈',confirm:true});
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[creating,setCreating]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [telegramId,setTelegramId]=useState(''),[type,setType]=useState<'GIFT_OR_PASS'|'GOOD_OR_BAD'|'OWNER_SPECIAL'>('GIFT_OR_PASS'),[title,setTitle]=useState(''),[giftMessage,setGiftMessage]=useState(''),[rewardType,setRewardType]=useState<'STARS'|'FREE_SPIN'|'XP'|'NOTE'>('STARS'),[amount,setAmount]=useState(5),[passCount,setPassCount]=useState(2);
 async function load(){setLoading(true);setError('');try{const data=await request<Api>('/api/admin/mechanics?initData='+encodeURIComponent(initData()),'GET');if(data.settings)setSettings(data.settings);}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить настройки.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 function toggle(id:string){setSettings(cur=>({...cur,enabled:{...cur.enabled,[id]:!cur.enabled[id]}}));}
 async function save(){setSaving(true);setError('');setMessage('');try{await request<Api>('/api/admin/mechanics','PATCH',{settings});setMessage('Настройки механик сохранены.');}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить настройки.');}finally{setSaving(false);}}
 async function createEvent(){const clean=telegramId.replace(/\D/g,'');if(!clean){setError('Укажи Telegram ID пользователя.');return;}setCreating(true);setError('');setMessage('');try{const data=await request<Api>('/api/admin/mechanics','POST',{telegramId:clean,type,title,message:giftMessage,rewardType,amount,passCount});setMessage(`Событие создано для ${data.event?.username??'пользователя'}.`);setTelegramId('');setGiftMessage('');}catch(e){setError(e instanceof Error?e.message:'Не удалось создать событие.');}finally{setCreating(false);}}
 return <AppShell title='Развлекательные механики' nav={false}><div className='space-y-4 pb-8'><Link to='/admin' className='inline-flex items-center gap-2 text-[11px] text-muted-foreground'><ArrowLeft className='size-3.5'/> Админ-панель</Link>
  <GlassCard glow className='px-4 py-4'><div className='flex items-start gap-3'><Sparkles className='mt-1 size-5 text-primary-glow'/><div><p className='text-[10px] uppercase tracking-[0.22em] text-muted-foreground'>Отдельные события</p><h1 className='mt-1 font-display text-xl uppercase'>Развлекательные механики</h1><p className='mt-1 text-[11px] leading-relaxed text-muted-foreground'>Это самостоятельные события. Они не списывают накопленные Stars и не уменьшают обязательный призовой фонд сезона.</p></div></div></GlassCard>
  {loading?<GlassCard className='px-4 py-8 text-center text-xs text-muted-foreground'>Загрузка…</GlassCard>:<><section className='space-y-2.5'>{MECHANICS.map(({id,title,description,icon:Icon})=><GlassCard key={id} className='px-3.5 py-3.5'><div className='flex items-start gap-3'><div className='grid size-9 shrink-0 place-items-center rounded-xl border border-glass-border bg-muted/20'><Icon className='size-4 text-primary-glow'/></div><div className='min-w-0 flex-1'><p className='text-sm font-semibold'>{title}</p><p className='mt-1 text-[10px] leading-relaxed text-muted-foreground'>{description}</p></div><button type='button' onClick={()=>toggle(id)} className={'inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[9px] font-semibold '+(settings.enabled[id]?'border-primary/30 bg-primary/10':'border-glass-border bg-muted/10 text-muted-foreground')}><Power className='size-3'/>{settings.enabled[id]?'Включено':'Выключено'}</button></div></GlassCard>)}</section>
  <GlassCard className='space-y-3 px-3 py-3'><div className='flex items-center gap-2'><HandCoins className='size-4 text-primary-glow'/><p className='text-sm font-semibold'>Параметры Gift or Pass</p></div><label className='block'><span className='mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground'>Максимум передач</span><input type='number' min={1} max={20} value={settings.passCount} onChange={e=>setSettings(cur=>({...cur,passCount:Math.min(20,Math.max(1,Number(e.target.value)||1))}))} className='admin-input w-full'/></label><label className='block'><span className='mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground'>Текст неудачи</span><textarea value={settings.failureText} onChange={e=>setSettings(cur=>({...cur,failureText:e.target.value}))} className='admin-input min-h-20 w-full resize-none'/></label><button disabled={saving} type='button' onClick={()=>void save()} className='inline-flex w-full items-center justify-center gap-2 rounded-xl border border-primary/30 bg-primary/10 px-3 py-2.5 text-xs font-semibold'><Sparkles className='size-4'/>{saving?'Сохраняем…':'Сохранить настройки'}</button></GlassCard>
  <GlassCard className='space-y-3 px-3 py-3'><div className='flex items-center gap-2'><Gift className='size-4 text-primary-glow'/><p className='text-sm font-semibold'>Создать событие для пользователя</p></div><p className='text-[10px] leading-relaxed text-muted-foreground'>Событие сохраняется в PostgreSQL и появляется у пользователя в Mini App. Выбери тип, награду и количество.</p><input value={telegramId} onChange={e=>setTelegramId(e.target.value.replace(/\D/g,''))} placeholder='Telegram ID' className='admin-input w-full' inputMode='numeric'/><select value={type} onChange={e=>setType(e.target.value as typeof type)} className='admin-input w-full'><option value='GIFT_OR_PASS'>🎁 Оставить или передать</option><option value='GOOD_OR_BAD'>🎲 Хороший или неудачный</option><option value='OWNER_SPECIAL'>✨ Особый подарок владельца</option></select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder='Заголовок события (необязательно)' className='admin-input w-full'/><textarea value={giftMessage} onChange={e=>setGiftMessage(e.target.value)} placeholder='Сообщение пользователю' className='admin-input min-h-20 w-full resize-none'/>{type==='GOOD_OR_BAD'?<label className='block'><span className='mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground'>Хороший результат, Stars</span><input type='number' min={0} max={100} value={amount} onChange={e=>setAmount(Math.min(100,Math.max(0,Number(e.target.value)||0)))} className='admin-input w-full'/></label>:<><div className='grid grid-cols-2 gap-2'><select value={rewardType} onChange={e=>setRewardType(e.target.value as typeof rewardType)} className='admin-input w-full'><option value='STARS'>⭐ Stars</option><option value='FREE_SPIN'>🎟️ Free Spin</option><option value='XP'>✨ XP</option><option value='NOTE'>Сообщение</option></select><input type='number' min={1} max={100} value={amount} disabled={rewardType==='NOTE'} onChange={e=>setAmount(Math.min(100,Math.max(1,Number(e.target.value)||1)))} className='admin-input w-full'/></div>{type==='GIFT_OR_PASS'&&<label className='block'><span className='mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground'>Передач для события</span><input type='number' min={0} max={20} value={passCount} onChange={e=>setPassCount(Math.min(20,Math.max(0,Number(e.target.value)||0)))} className='admin-input w-full'/></label>}</>}<button disabled={creating} type='button' onClick={()=>void createEvent()} className='inline-flex w-full items-center justify-center gap-2 rounded-xl border border-primary/35 bg-primary/10 px-3 py-2.5 text-xs font-semibold'><Gift className='size-4'/>{creating?'Создаём…':'Создать и показать пользователю'}</button></GlassCard>
  {message&&<GlassCard className='border-primary/25 bg-primary/5 px-4 py-3 text-[11px]'>{message}</GlassCard>}{error&&<GlassCard className='border-destructive/30 bg-destructive/5 px-4 py-3 text-[11px] text-destructive'>{error}</GlassCard>}</>}</div></AppShell>;
}