import { createFileRoute } from "@tanstack/react-router";
import { authenticateAdmin } from "@/server/auth/access";
import { query } from "@/server/db";

type AuditRow={id:string;created_at:string;actor:string|null;role:"OWNER"|"ADMIN"|null;action:string;entity_type:string;entity_id:string|null;target_label:string|null;before_data:Record<string,unknown>|null;after_data:Record<string,unknown>|null};
const TEST_FILTER=`(ad.id IS NULL OR ad.is_test=FALSE) AND NOT EXISTS (SELECT 1 FROM users ut WHERE ut.is_test=TRUE AND (a.entity_id=ut.id::text OR a.after_data->>'userId'=ut.id::text OR a.before_data->>'userId'=ut.id::text))`;
export const Route=createFileRoute("/api/admin/audit")({server:{handlers:{GET:async({request})=>{try{const url=new URL(request.url);await authenticateAdmin(url.searchParams.get("initData")??"");const search=(url.searchParams.get("search")??"").trim();const limit=Math.min(200,Math.max(1,Number(url.searchParams.get("limit")??100)));const pattern=`%${search.replaceAll("%","\\%").replaceAll("_","\\_")}%`;const result=await query<AuditRow>(`SELECT a.id::text,a.created_at::text,COALESCE(ad.username,ad.telegram_id::text) AS actor,ad.role,a.action,a.entity_type,a.entity_id,
 CASE
  WHEN a.entity_type='user' THEN COALESCE((SELECT CASE WHEN u.username IS NOT NULL THEN '@'||REGEXP_REPLACE(u.username,'^@','') ELSE NULL END FROM users u WHERE u.id::text=a.entity_id),'Пользователь')
  WHEN a.entity_type='spin' THEN COALESCE((SELECT COALESCE('@'||REGEXP_REPLACE(u.username,'^@',''),u.first_name||' · ID '||u.telegram_id::text) || ' · ' || COALESCE(p.title,'Прокрутка') FROM spins s JOIN users u ON u.id=s.user_id LEFT JOIN prizes p ON p.id=s.prize_id WHERE s.id::text=a.entity_id),'Прокрутка')
  WHEN a.entity_type='payout' THEN COALESCE((SELECT CASE WHEN py.note LIKE 'WITHDRAWAL_REQUEST%' THEN 'Вывод Stars · @'||COALESCE(REGEXP_REPLACE(u.username,'^@',''),u.telegram_id::text) ELSE COALESCE(p.title,'Выплата')||' · @'||COALESCE(REGEXP_REPLACE(u.username,'^@',''),u.telegram_id::text) END FROM payouts py JOIN users u ON u.id=py.user_id LEFT JOIN prizes p ON p.id=py.prize_id WHERE py.id::text=a.entity_id),'Выплата')
  WHEN a.entity_type='season' THEN COALESCE((SELECT s.name||' · '||s.code FROM seasons s WHERE s.id::text=a.entity_id),'Сезон')
  WHEN a.entity_type='prize' THEN COALESCE((SELECT p.title||COALESCE(' · '||p.subtitle,'') FROM prizes p WHERE p.id::text=a.entity_id),'Приз')
  ELSE COALESCE(a.after_data->>'username',a.after_data->>'userLabel',a.entity_type)
 END AS target_label,a.before_data,a.after_data FROM audit_logs a LEFT JOIN admins ad ON ad.id=a.admin_id WHERE ${TEST_FILTER} AND ($2='' OR a.action ILIKE $1 OR a.entity_type ILIKE $1 OR COALESCE(a.entity_id,'') ILIKE $1 OR COALESCE(ad.username,'') ILIKE $1 OR COALESCE(ad.telegram_id::text,'') ILIKE $1) ORDER BY a.created_at DESC LIMIT $3`,[pattern,search,limit]);const counts=await query<{total:string;admin_events:string;system_events:string}>(`SELECT COUNT(*)::text AS total,COUNT(*) FILTER(WHERE a.admin_id IS NOT NULL)::text AS admin_events,COUNT(*) FILTER(WHERE a.admin_id IS NULL)::text AS system_events FROM audit_logs a LEFT JOIN admins ad ON ad.id=a.admin_id WHERE ${TEST_FILTER}`);return Response.json({ok:true,counts:{total:Number(counts.rows[0]?.total??0),adminEvents:Number(counts.rows[0]?.admin_events??0),systemEvents:Number(counts.rows[0]?.system_events??0)},items:result.rows});}catch(error){console.error("Audit API failed:",error instanceof Error?error.message:error);return Response.json({ok:false,code:"AUDIT_FAILED"},{status:401});}}}}});
