import { createFileRoute } from "@tanstack/react-router";
import { authenticateAdmin } from "@/server/auth/access";
import { query } from "@/server/db";

type GiftRow={id:string;username:string;telegramId:string;gift:string;status:"Подготовлен"|"Выдан"|"Ожидает";message:string;createdAt:string;issuedAt:string|null};

async function readGifts(){
  const result=await query<{value:GiftRow[]}>(`SELECT COALESCE(value,'[]'::jsonb) AS value FROM app_settings WHERE key='owner_gifts' LIMIT 1`);
  return result.rows[0]?.value??[];
}

export const Route=createFileRoute("/api/admin/owner-gifts")({server:{handlers:{
 GET:async({request})=>{try{await authenticateAdmin(new URL(request.url).searchParams.get("initData")??"");return Response.json({ok:true,gifts:await readGifts()});}catch{return Response.json({ok:false,code:"OWNER_GIFTS_FAILED"},{status:401});}},
 POST:async({request})=>{try{const body=await request.json() as {initData?:unknown;username?:unknown;telegramId?:unknown;gift?:unknown;message?:unknown};const admin=await authenticateAdmin(typeof body.initData==='string'?body.initData:'');const telegramId=String(body.telegramId??'').replace(/\D/g,'');if(!telegramId)return Response.json({ok:false,code:'INVALID_TELEGRAM_ID'},{status:400});const gift=String(body.gift??'').trim();if(!gift)return Response.json({ok:false,code:'INVALID_GIFT'},{status:400});const row:GiftRow={id:`og_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,username:String(body.username??'').trim()||'—',telegramId,gift,status:'Подготовлен',message:String(body.message??'').trim().slice(0,1000),createdAt:new Date().toISOString(),issuedAt:null};const gifts=await readGifts();gifts.unshift(row);await query(`INSERT INTO app_settings(key,value) VALUES('owner_gifts',$1::jsonb) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()`,[JSON.stringify(gifts.slice(0,500))]);await query(`INSERT INTO audit_logs(admin_id,action,entity_type,entity_id,after_data) VALUES($1::uuid,'OWNER_GIFT_CREATED','setting','owner_gifts',$2::jsonb)`,[admin.id,JSON.stringify({telegramId,gift})]);return Response.json({ok:true,gift:row});}catch(error){return Response.json({ok:false,code:error instanceof Error?error.message:'OWNER_GIFT_CREATE_FAILED'},{status:400});}},
 PATCH:async({request})=>{try{const body=await request.json() as {initData?:unknown;id?:unknown;status?:unknown};const admin=await authenticateAdmin(typeof body.initData==='string'?body.initData:'');const id=String(body.id??'');const status=body.status==='Выдан'?'Выдан':body.status==='Ожидает'?'Ожидает':null;if(!id||!status)return Response.json({ok:false,code:'INVALID_UPDATE'},{status:400});const gifts=await readGifts();const index=gifts.findIndex((gift)=>gift.id===id);if(index<0)return Response.json({ok:false,code:'GIFT_NOT_FOUND'},{status:404});gifts[index]={...gifts[index],status,issuedAt:status==='Выдан'?new Date().toISOString():null};await query(`INSERT INTO app_settings(key,value) VALUES('owner_gifts',$1::jsonb) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()`,[JSON.stringify(gifts)]);await query(`INSERT INTO audit_logs(admin_id,action,entity_type,entity_id,after_data) VALUES($1::uuid,'OWNER_GIFT_UPDATED','setting','owner_gifts',$2::jsonb)`,[admin.id,JSON.stringify({id,status})]);return Response.json({ok:true,gifts});}catch(error){return Response.json({ok:false,code:error instanceof Error?error.message:'OWNER_GIFT_UPDATE_FAILED'},{status:400});}},
}}});
